### ISSUE TITLE
Site gives you a skill point one level too early

### ISSUE THREAD

**Issue by LokIsLoki** [seigler/bl3skills.com#1]
You can see here https://youtu.be/X_aGpsojdQg?t=1288 from 21:34 to 22:10 that he has 1 skillpoint spent at level 4, not 2 skillpoints (in this example it is used in the green tree), and he has 0 extra skill points available
Meaning you get your first skillpoint at level 4

**Comment by seigler** [comment]
This is a more specific instance of #6 -- we'll have to wait and see how the skill points and level are related.
