### ISSUE TITLE
You gain your first skill point at level 3 and you action skill unlocks for free.

### ISSUE THREAD

**Issue by Squally628** [seigler/bl3skills.com#11]
https://youtu.be/9BYWVHa1c4s

At 0:13 of this video you see Moze at level 6 and from the beginning it says to “Unlock Action Skill” and at 0:18 you see “Action Skills Unlocked” without even using points at all. When you see the skill tree you will see on the left side she has 4 skill points, remember she’s at level 6, so that means at level 3 you unlock action skills automatically without using points and you gain a skill point at level 3. 

Well that’s according to this video but I just wanted to let you know.

**Comment by seigler** [comment]
Thank you! I just merged #1 which should resolve this issue.
