### ISSUE TITLE
Values and more are outdated.

### ISSUE THREAD

**Issue by Ravenjim** [seigler/bl3skills.com#13]
With the launch of the BL3 skill calculator on their official site, many skills are shown to be changed. Most of em are just value changes (like amara's find your center 22% melee boost to 100%) others are skills being swapped in rows( zane's seeing red, and death follows close.

I checked your values with the values shown on videos back when the chars were shown and they are true to those videos, Fl4k videos tho are also true to the BL3 Site values tho. Which leads me to believe values have been indeed updated.

**Comment by ColinRoxs** [comment]
can't wait until the calculator get updated, very useful for making theoretical post dlc builds, (assuming the lvl cap post dlc is 70)

**Comment by FromDarkHell** [comment]
I ended up gathering the icons for FL4K (including skill name): [skillIcons.zip](https://github.com/seigler/bl3skills.com/files/3489031/skillIcons.zip)

**Comment by jvanalst** [comment]
This is stupid easy to fix, but based on activity I'm not sure @seigler is actually maintaining the project anymore?

I'd be willing to put in a PR, but I'd like some reassurance it'd actually get merged if I took the time to translate all the official descriptions to skills.js under https://github.com/seigler/bl3skills.com/tree/master/src/pages

It's just a couple of hours of time consuming cut and paste type work.

**Comment by seigler** [comment]
I'm not actively maintaining right now, but I will definitely merge updates.

**Comment by jvanalst** [comment]
I'll work on this at lunch.

**Comment by seigler** [comment]
Thanks @jvanalst for the Siren update, it's live now.

**Comment by seigler** [comment]
FL4K's tree is now live with the latest data.

**Comment by chronofreak** [comment]
@Ravenjim I've overhauled all of the skills to make sure they are in line with the latest values. This issue can be closed.

**Comment by seigler** [comment]
Oh, right! Thanks
