### ISSUE TITLE
Fl4k skills not showing

### ISSUE THREAD

**Issue by AnnoyingNavi** [seigler/bl3skills.com#14]
![Capture bl3](https://user-images.githubusercontent.com/51049141/63213577-df0efa80-c0c2-11e9-9c69-5cdef101873c.PNG)

Every other character works fine except Fl4k, Tested on a PC and laptop and got same results

**Comment by TheDiggster13** [comment]
Also having this issue

**Comment by FauxPirate** [comment]
I'm not a fan of the official skill trees on borderlands.com.  I much prefer your easy-to-see and easy-to-navigate trees.  Please let us know when your FL4K tree is ready!

**Comment by J-888** [comment]
It's because (at least) all flak skill images are missing

**Comment by mrspartak** [comment]
1 month no reaction, I guess OP will not come to help

**Comment by jvanalst** [comment]
See: https://github.com/seigler/bl3skills.com/issues/13#issuecomment-520157696

**Comment by mattcopas** [comment]
This isnt working because the Fl4K tree needs filling in: https://github.com/seigler/bl3skills.com/blob/master/src/pages/Beastmaster/skills.js

An example of how these work can be found in Zanes tree here: https://github.com/seigler/bl3skills.com/blob/master/src/pages/Operative/skills.js

**Comment by jvanalst** [comment]
The actual tree fill I can add as part of https://github.com/seigler/bl3skills.com/issues/13.

Not sure what to do about the missing talent icons yet.

**Comment by J-888** [comment]
@seigler I fixed this on #15, could you merge the pull request so anyone can easily add the tests? Thanks

**Comment by garyking** [comment]
The icons now appear, but hovering them doesn't provide the correct text.

**Comment by rlindsey28** [comment]
PR up for adding data to FL4K's skills.js

https://github.com/seigler/bl3skills.com/pull/18

**Comment by seigler** [comment]
Thank you @rlindsey28 for doing this! The update is live.
