### ISSUE TITLE
Skilltrees not progressing correctly

### ISSUE THREAD

**Issue by r34kt0r** [seigler/bl3skills.com#2]
When putting one point into the mid-tree capstone / gamechanger it should progress to the next tier, in the attached picture theres an example, that should unlock 4th row.

thanks for making one this quick btw 

![bug](https://user-images.githubusercontent.com/34202016/57382973-3f31fe80-71ae-11e9-972a-9be25b47b318.PNG)
![grafik](https://user-images.githubusercontent.com/34202016/57382980-42c58580-71ae-11e9-84fd-86a45c5ba200.png)

**Comment by seigler** [comment]
As far as I've seen, the tiers unlock with every five points spent. That means to continue advancing "Under Cover" as in your screenshots, you need to invest more points in the first two tiers. I believe this is working as intended, although I agree that Gearbox's design may be confusing to some.
