### ISSUE TITLE
Typos in Amara's skill tree

### ISSUE THREAD

**Issue by O-Deka-K** [seigler/bl3skills.com#24]
**Describe the bug**
For Amara -> Catharsis, "Whenrbrt Amara riggers" should be "When**ever** Amara **t**riggers".
For Amara -> Conflux, "Whenever Ammara" should be "Whenever A**m**ara".

**To Reproduce**
1. Go to 'Amara'
2. In the 'Fist of the Elements' skill tree, hover over 'Catharsis' or 'Conflux'
3. See error

**Comment by jmichelin** [comment]
https://github.com/seigler/bl3skills.com/pull/25

**Comment by seigler** [comment]
This is now fixed. Thank you for noticing!
