### ISSUE TITLE
Plz update incorrect Skills Image

### ISSUE THREAD

**Issue by Hardkore007** [seigler/bl3skills.com#26]
**Is your feature request related to a problem? Please describe.**
--Not a coder, so can't help, had to create a Github acct just to type this...but...for the past ~6 weeks, I've noticed some of the images for various skills, don't match the images in-game.  An example is Amara's Conflux skill.  The real image should be sorta like the Yin-Yang symbol, only with electric clouds (hard to describe)...but this guide has it as a fist holding lightning.  Not the end of the world, but I when I'm in a different class and I pick up a CM, and I'm trying to determine what skills that class mod has (and if I should keep/drop it), it makes it confusing/hard to do.  Thanks.

**Describe the solution you'd like**
--Just needs someone to check current classes/skills' images vs whats shown on the site...then change them.
**Describe alternatives you've considered**
--Other than to not update the images, that's the only solution for fixing it, not difficult, just takes time.
**Additional context**
--Sorry, not screenshots since on PS4 vs my laptop here...but just check various the various classes skill trees' images vs whats on the site, you'll see what I mean.  It's probably a 1-3% issue so not huge.  thanks again

**Comment by chronofreak** [comment]
All icons have been updated. This issue can be closed.
