### ISSUE TITLE
Reset button is active only in text region

### ISSUE THREAD

**Issue by MichelleElliott** [seigler/bl3skills.com#3]
The Reset button works, but only if the cursor is in the text region.  The remainder of the button rectangle is unresponsive.  
Environment: macOS 10.13.6. 
Chrome Version 74.0.3729.131, Safari Version 12.1 (13607.1.40.1.5) and Firefox 66.0.5.

**Comment by seigler** [comment]
Thank you! This is fixed.

**Comment by MichelleElliott** [comment]
Happy to help. My programming skills don’t include web dev or I would have created a PR.
