### ISSUE TITLE
Moze skill points

### ISSUE THREAD

**Issue by DetMig** [seigler/bl3skills.com#6]
In the E3 gameplay we can see that Moze has 5 skill points at lvl 7
https://youtu.be/bUBHGl6LPV8?t=855
but in this gameplay Zane has 7 skill points at lvl 10
https://youtu.be/V0JlKu_IJhw?t=54

so either they changed it or it depends on each playable character

**Comment by seigler** [comment]
Well. Thanks for pointing this out, I thought I had just gotten the level calculation wrong. I'll leave this issue open until we have a good answer. Thank you

**Comment by seigler** [comment]
Unless we get new information I think we can call this one resolved, based on recent gameplay videos.
