### ISSUE TITLE
Skills not updated

### ISSUE THREAD

**Issue by RetiQlum** [seigler/bl3skills.com#61]
**Describe the bug**
There have been many changes since the app was written.

**To Reproduce**
Look at the Moze skills Scrappy and Torgue Cross-Promotion.  Both now deal increased damage.   Experimental Munitions now does a lot more.

**Expected behavior**
Skills updated to match current effects.

**Screenshots**

**Device**

**Additional context**
This shouldn't take too long to implement.

**Comment by chronofreak** [comment]
@RetiQlum I've been updating the skills every time a new hotfix or patch is released. The changes you mentioned were already updated on 4/26 via pull request #59. Try reloading the bl3skills.com page or clear your browser's cache.

**Comment by RetiQlum** [comment]
OK.  I reloaded the page and it did nothing.  Cleared the cache for the site and it worked.

**Comment by RetiQlum** [comment]
Thanks.
________________________________
