### ISSUE TITLE
A way to select Augments

### ISSUE THREAD

**Issue by JinsTonik** [seigler/bl3skills.com#8]
Now that we have clear understanding of how skill augments work for the 3 revealed VHs is it possible to implement a way to select them along with a "Currently equipped Action Skill". The 2 skills for Zane with 2 augments each, 2 mech-guns for Moze with 1 augment each and an action skill, element and augment for Amara.

Even if they can be swapped on the fly this is a big part of the build and it would be awesome to have as a functionality. Your work is much appreciated for build-theorycrafters like me, thank you.

**Comment by IhsanMujdeci** [comment]
Yo, Im a senior full stack dev with react skills, I could make this feature. Sounds cool
Do you have any thing you've planned yet for this feature?

**Comment by chronofreak** [comment]
@IhsanMujdeci Does your offer to work on adding selectable skills and augments still stand? As stated in another post, @seigler isn't actively working on this project, but he is around to merge any updates sent his way. Being able to select skills and augments is the only thing missing from this planner and would be a great addition.
